### ISSUE TITLE
Does User-space drivers, also available for ordinary Android phone?

### ISSUE THREAD

**Issue by helpme2k2** [androidthings/contrib-drivers#123]
Hi all,

Sorry if my question sound silly to you, but I really need to build an app that simulate a HID device to inject hardware event to be accessed by other apps. I found User-space drivers on https://developer.android.com/things/sdk/drivers and it looks like exactly what I needed. Except, it is listed under Android Things. 

Does User-space drivers also available for commercial Android phone? Thanks.

Elton

**Comment by Fleker** [comment]
No user-space drivers are only an api that can be used on Android Things devices.
