### ISSUE TITLE
ht16k33 driver doesn't cater for dot on final character

### ISSUE THREAD

**Issue by Jatra** [androidthings/contrib-drivers#13]
Length test is before the check to see if the '.' can be added to the previous character.

(Also, Font file can contain '.' which makes logic a little simpler)

Changes at https://github.com/Jatra/contrib-drivers/commit/2161e2c0bab942e535d2d6dcc4a55a9649c76427

**Comment by proppy** [comment]
Can you submit this as a pull request?

**Comment by frankkienl** [comment]
I had the same issue, posted on code.google
https://code.google.com/p/android/issues/detail?id=231264
tracking it here is okay with me.
