### ISSUE TITLE
[RainbowHat] openBuzzer() not available 

### ISSUE THREAD

**Issue by StefMa** [androidthings/contrib-drivers#15]
The latest [commit](https://github.com/androidthings/contrib-drivers/blob/efdbd9cb84895ea0cb1414c258f696c55afe8688/) from the RainbowHat driver say something about `openBuzzer()` inside the [`README.md`](https://github.com/androidthings/contrib-drivers/blob/efdbd9cb84895ea0cb1414c258f696c55afe8688/rainbowhat/README.md).

Unfortunately isn't there any `openBuzzer()` method inside the [`RainbowHat` class](https://github.com/androidthings/contrib-drivers/blob/efdbd9cb84895ea0cb1414c258f696c55afe8688/rainbowhat/src/main/java/com/google/android/things/contrib/driver/rainbowhat/RainbowHat.java) but a `openPiezo()`

What should we do now?
Change the `README` or method? 🤔

**Comment by jdkoren** [comment]
We have this fixed internally, will close once the update is published.

**Comment by proppy** [comment]
Fixed with 61c5a0ae879379d91d0fa5ae4e432d42ea3ef99c
