### ISSUE TITLE
USB diver access on raspberry pi 3

### ISSUE THREAD

**Issue by PratikGajera** [androidthings/contrib-drivers#2]
Hello Team,

Successfully flash iot_rpi3.img image in raspberrypi 3. Now i want to access USB device.But i didn't know that how can access usb device over Android Things OS in raspberryPi 3.
Please Help me as soon as possible!!

**Comment by proppy** [comment]
@PratikGajera As mentioned in the [release notes](https://developer.android.com/things/preview/releases.html) USB APIs are currently disabled in the Developer Preview RC1.

I would encourage you to track this [feature request](https://code.google.com/p/android/issues/detail?id=230305) on b.android.com to track the progress around this. (This repository is used to release user-space contrib-drivers)

**Comment by PratikGajera** [comment]
Thank you proppy.
