### ISSUE TITLE
Bluetooth support on RPi3

### ISSUE THREAD

**Issue by StevenRudenko** [androidthings/contrib-drivers#3]
Is there any plans to support bluetooth for Things devices like RPi3? I think BLE support is essential part of making IoT solutions.

There is [RTAndroid](https://git.embedded.rwth-aachen.de/rtandroid/downloads/raspberry-pi/) project which has BLE support. Probably it would be easy to use part of their codebase to make Things BLE ready.

**Comment by proppy** [comment]
@StevenRudenko As [mentioned](https://developer.android.com/things/preview/releases.html) in the release notes Bluetooth is currently disabled in the Developer Preview RC1.

I would encourage you to file a [feature request](https://code.google.com/p/android/issues/entry?template=Android%20Things%20feature%20request) on b.android.com to track the progress around this. (This repository is used to release [user-space contrib-drivers](https://developer.android.com/things/sdk/drivers/index.html))
