### ISSUE TITLE
Speaker does not have play(tone, duration) method

### ISSUE THREAD

**Issue by tomaszrykala** [androidthings/contrib-drivers#35]
The readme for PWM Speaker describes an overloaded `play()` method that takes a tone and a duration as arguments. The driver however, supplies only a method that allows the tone.

readme source:
https://github.com/androidthings/contrib-drivers/tree/master/pwmspeaker

extract:
```java
// Make it play:

try {
    mSpeaker.play(440 /* tone */, 3000L /* duration */);
} catch (IOException e) {
    // error setting speaker
}
```

The only currently existing method:
```java
    public void play(double frequency) throws IOException, IllegalStateException {
...
    }
```

**Comment by proppy** [comment]
Sounds like a documentation bug :)

**Comment by tomaszrykala** [comment]
Can update the documentation to address this, but is there somehow we could expand on this, admiteddly not ideal, solution? https://github.com/androidthings/contrib-drivers/pull/36

**Comment by tomaszrykala** [comment]
Thank you for the input. I will update the documentation in the meantime.

**Comment by mangini** [comment]
@tomaszrykala Supporting duration essentially means having a sequencer in a separate thread that handles the timers, so it's not trivial. We have an initial implementation in our internal code review. Can you open a separate "enhancement" issue so we can keep track of it? Thanks!

**Comment by tomaszrykala** [comment]
@mangini Here it is. https://github.com/androidthings/contrib-drivers/issues/38 Thanks.

**Comment by tomaszrykala** [comment]
This is closed by https://github.com/androidthings/contrib-drivers/pull/37
