### ISSUE TITLE
Missing LEDSTRIP_LENGTH constant

### ISSUE THREAD

**Issue by plattysoft** [androidthings/contrib-drivers#4]
It is used on the sample code, but it is not present on the code.

**Comment by jdkoren** [comment]
@plattysoft Just to clarify, this is for the APA102 driver?

**Comment by proppy** [comment]
I Think @plattysoft is referring to the RainbowHat snippets:
https://github.com/androidthings/contrib-drivers/tree/master/rainbowhat#sample-usage

They mention `RainbowHat.LEDSTRIP_LENGTH]` but that doesn't exist yet in the driver.

**Comment by plattysoft** [comment]
Yes, that is it. It is just a constant with value 7, very simple to fix.

**Comment by proppy** [comment]
@plattysoft yep, [contributions](https://github.com/androidthings/contrib-drivers/blob/master/CONTRIBUTING.md) are welcome!

**Comment by ipereziriarte** [comment]
@proppy I've created a small patch for the issue.
https://github.com/androidthings/contrib-drivers/pull/7

**Comment by proppy** [comment]
Fixed with e3a4cff6cfa4504f4647b29a4402eb3e77235ca1
