### ISSUE TITLE
Some driver samples support register() some do not

### ISSUE THREAD

**Issue by salamanders** [androidthings/contrib-drivers#46]
It would be nice to have guidance on if drivers should all support register() or if it is optional, and if so, when it should/should not be supported.

**Comment by mangini** [comment]
Hi, @salamanders 
All drivers that can register with the Android framework, using the UserDriver library, should have a UserDriver class and the correspondent register() method(s). For some drivers, there's no possible framework integration. For example, there's no UserDriver API for integrating the apa102 driver with the Android framework. In those cases, we only provide a driver that abstracts the low level interface.
If you see a driver that could have an equivalent UserDriver integration but does not, please open a specific bug and we will take a look.
