### ISSUE TITLE
ssd1306 driver should support arbitrary height and width

### ISSUE THREAD

**Issue by proppy** [androidthings/contrib-drivers#53]
Currently it's [hardcoded](https://github.com/androidthings/contrib-drivers/blob/master/ssd1306/src/main/java/com/google/android/things/contrib/driver/ssd1306/Ssd1306.java#L36) to `128x64`.

**Comment by mangini** [comment]
fixed in version 0.4

**Comment by proppy** [comment]
Fixed w/ https://github.com/androidthings/contrib-drivers/commit/a0092cffc0f41aafe90bab138c83141fb851f05b
