### ISSUE TITLE
This looks to be inverted -> LogicState.PRESSED_WHEN_HIGH and  LogicState.PRESSED_WHEN_LOW 

### ISSUE THREAD

**Issue by TegenArade** [androidthings/contrib-drivers#6]
I am getting the opposite of what this stats supposed to do->  LogicState.PRESSED_WHEN_HIGH and  LogicState.PRESSED_WHEN_LOW

**Comment by jdkoren** [comment]
@TegenArade Are you using a pull-up resistor or a pull-down resistor? With `LogicState.PRESSED_WHEN_LOW` you would need to use a pull-up resistor, and unfortunately not all the samples are consistent about which logic state they use.

**Comment by TegenArade** [comment]
@jdkoren I am using base shield, so I am not sure which one its using. 
Thanks  for the answer.
