### ISSUE TITLE
Issue with VoiceHat: Constructor does not set mAudioFormat

### ISSUE THREAD

**Issue by remy-beaumont** [androidthings/contrib-drivers#69]
The constructor of VoiceHat does not assign mAudioFormat to audioFormat.

This will result in a NullPointerException in com.google.android.things.audio.AudioConfiguration.encodingFromAudioFormat when you either call AudioInputUserDriver() or registerAudioOutputDriver()

**Comment by Fleker** [comment]
Thanks for noting that. I just noticed that a few hours ago. I'm working on a fix for it now.

**Comment by Fleker** [comment]
This was fixed in a9b48beb37435d8dfe9f7a787b1027359a2442a7
