### ISSUE TITLE
Driver for ar1100 touch panel

### ISSUE THREAD

**Issue by Swat24** [androidthings/contrib-drivers#79]
Hello, I need to use lcd with touch panel in my project, touch is controlled by ar1100. Android things not have driver for this touch, what I need to use this panel? How I can configure android? Lcd connected via hdmi work good.

**Comment by TwistedTransistor** [comment]
If you connect the ar1100 to the device via USB, it automatically works as a mouse.  So nothing for you to do there.

If you want to connect via UART, then just use the UART driver already available to talk to the ar1100.
