### ISSUE TITLE
AlphanumericDisplay class missing

### ISSUE THREAD

**Issue by TiksGanesh** [androidthings/contrib-drivers#83]
Hi today i included library inti AndroidThings projcet using AndroidStudio.
Below classes are missing from library

AlphanumericDisplay, Speaker,
Servo,Button,
ButtonInputDriver,Apa102,
Bmx280SensorDriver,Bmx280

**Comment by Fleker** [comment]
You may need to add them separately to your `build.gradle` until the newer versions of the `RainbowHat` dependency is re-generated, as per fc2e222b36a071f427ac380b579442fb9ea27418

**Comment by Fleker** [comment]
If you update to the latest RainbowHat version you should see the classes.

`implementation 'com.google.android.things.contrib:driver-rainbowhat:0.8'`
