### ISSUE TITLE
Voicehat support for NXP i.MX 7Dual

### ISSUE THREAD

**Issue by rachitmishra** [androidthings/contrib-drivers#84]
Hi, Is it possible to use voicehat driver with Pico developer kit?

**Comment by Fleker** [comment]
By default, [the imx7 I/O](https://developer.android.com/things/hardware/imx7d-pico-io.html) does not support I2S, it's on a different set of pins. The VoiceHat peripherals, such as the LED and button, can be opened using the `VoiceHat.openLed(pinname)` and `VoiceHat.openButton(pinname)` methods.

Technically, yes you can use the VoiceHat driver with the imx7.

**Comment by rachitmishra** [comment]
yup, I was wondering if i can get the right set of pings to open, i think i can control the mic as well as the speaker. thank you 👍

**Comment by Fleker** [comment]
You can see some of the matches in the [Google Assistant sample](https://github.com/androidthings/sample-googleassistant/blob/master/app/src/main/java/com/example/androidthings/assistant/BoardDefaults.java).

**Comment by rachitmishra** [comment]
Great! Thanks, I was looking at the python samples :'D
