### ISSUE TITLE
APA102 Driver for WS2812b

### ISSUE THREAD

**Issue by prasha-findmind** [androidthings/contrib-drivers#92]
Can I use the APA102 Driver for WS2812b?
What are the modifications that should be done to use it?

**Comment by Ic-ks** [comment]
I wrote a driver for these LEDs: https://github.com/Ic-ks/contrib-drivers/tree/master/ws2812b  I did already a pull request (https://github.com/androidthings/contrib-drivers/pull/76)

**Comment by prasha-findmind** [comment]
the jcentre page is not opening, so I am not able to figure out the latest version, can you please let me know the latest version

**Comment by prasha-findmind** [comment]
https://bintray.com/google/androidthings/contrib-driver-ws2812b/_latestVersion

it says this link is not valid I get a page not found error can you do something about it?

**Comment by prasha-findmind** [comment]
I also tried searching in https://bintray.com/google/androidthings this link I couldn't find your driver, so please help me out

**Comment by Ic-ks** [comment]
Sorry for the late response. You can import the driver by cloning the repository (https://github.com/Ic-ks/contrib-drivers.git) and using the import function of Android Studio in your project: File->New->Import-Module. Then select <CLONE_DIR>/contrib-drivers/ws2812b. The import function will copy ws2812 driver to your project. If you don't want a copy of the driver you could create a relative path dependency like described here: https://stackoverflow.com/questions/24975745/gradle-dependencies-compile-project-by-relative-path
