### ISSUE TITLE
[driver]How to support 1-wire just like DS18B20?

### ISSUE THREAD

**Issue by 562134391** [androidthings/contrib-drivers#93]

**Comment by Fleker** [comment]
There's no direct support for a OneWire bus on any Android Things SOM, although there are ways you can implement the OneWire protocol using a [UART bus](https://github.com/dword1511/onewire-over-uart). I don't have an example, but that repository is one example of the circuit that you can build. The code there can serve as a good starting point for implementing the protocol.
