### ISSUE TITLE
jcenter version of Rainbow HAT not updated to DP8

### ISSUE THREAD

**Issue by plattysoft** [androidthings/contrib-drivers#99]
InputDriver.Builder has changed, button driver has the changes and the dependency in Rainbow HAT meta-driver has been updated in master, but that version is not uploaded on jcenter, therefore if you try to implement a button via the Rainbow Driver, it crashes on runtime.

**Comment by mangini** [comment]
Thanks for pointing this out, @plattysoft . Just published a new version of all related drivers and rainbowhat (11). The driver list in https://github.com/androidthings/contrib-drivers#current-contrib-drivers is updated as well. Let me know if you still have problems.
